apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-flask-app
  name: my-flask-app-svc-internal
  namespace: exam-29
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-flask-app
  type: ClusterIP
status:
  loadBalancer: {}
