apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: bobur
    project: practice
  name: nginx1
  namespace: exam-29
spec:
  containers:
  - image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
